In [2]:
import pandas as pd

ratings = pd.read_csv(
    "ml-1m/ratings.dat",
    sep="::",
    engine="python",
    encoding="latin-1",
    names=["userId", "movieId", "rating", "timestamp"],
    header=None
)

movies = pd.read_csv(
    "ml-1m/movies.dat",
    sep="::",
    engine="python",
    encoding="latin-1",
    names=["movieId", "title", "genres"],
    header=None
)

In [3]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy


In [4]:
ratings.head()

,userId,movieId,rating,timestamp
0,1,1193,5,978300760
1,1,661,3,978302109
2,1,914,3,978301968
3,1,3408,4,978300275
4,1,2355,5,978824291


In [5]:
movies["content"] = movies["title"] + " " + movies["genres"].str.replace("|", " ")
movies.head()

,movieId,title,genres,content
0,1,Toy Story (1995),Animation|Children's|Comedy,Toy Story (1995) Animation Children's Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy,Jumanji (1995) Adventure Children's Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance,Grumpier Old Men (1995) Comedy Romance
3,4,Waiting to Exhale (1995),Comedy|Drama,Waiting to Exhale (1995) Comedy Drama
4,5,Father of the Bride Part II (1995),Comedy,Father of the Bride Part II (1995) Comedy


In [6]:
data = ratings.merge(movies, on="movieId")
data.head(20)

,userId,movieId,rating,timestamp,title,genres,content
0,1,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama,One Flew Over the Cuckoo's Nest (1975) Drama
1,1,661,3,978302109,James and the Giant Peach (1996),Animation|Children's|Musical,James and the Giant Peach (1996) Animation Chi...
2,1,914,3,978301968,My Fair Lady (1964),Musical|Romance,My Fair Lady (1964) Musical Romance
3,1,3408,4,978300275,Erin Brockovich (2000),Drama,Erin Brockovich (2000) Drama
4,1,2355,5,978824291,"Bug's Life, A (1998)",Animation|Children's|Comedy,"Bug's Life, A (1998) Animation Children's Comedy"
5,1,1197,3,978302268,"Princess Bride, The (1987)",Action|Adventure|Comedy|Romance,"Princess Bride, The (1987) Action Adventure Co..."
6,1,1287,5,978302039,Ben-Hur (1959),Action|Adventure|Drama,Ben-Hur (1959) Action Adventure Drama
7,1,2804,5,978300719,"Christmas Story, A (1983)",Comedy|Drama,"Christmas Story, A (1983) Comedy Drama"
8,1,594,4,978302268,Snow White and the Seven Dwarfs (1937),Animation|Children's|Musical,Snow White and the Seven Dwarfs (1937) Animati...
9,1,919,4,978301368,"Wizard of Oz, The (1939)",Adventure|Children's|Drama|Musical,"Wizard of Oz, The (1939) Adventure Children's ..."


In [7]:
documents = movies['content'].fillna("").tolist()
print(type(documents))
print(documents[:10])

<class 'list'>
["Toy Story (1995) Animation Children's Comedy", "Jumanji (1995) Adventure Children's Fantasy", 'Grumpier Old Men (1995) Comedy Romance', 'Waiting to Exhale (1995) Comedy Drama', 'Father of the Bride Part II (1995) Comedy', 'Heat (1995) Action Crime Thriller', 'Sabrina (1995) Comedy Romance', "Tom and Huck (1995) Adventure Children's", 'Sudden Death (1995) Action', 'GoldenEye (1995) Action Adventure Thriller']


In [8]:
tokenized_docs = []

for doc in documents:
    doc = doc.lower()
    doc = doc.replace("(","").replace(")","")
    doc = doc.replace(",","").replace(".","")
    doc = doc.replace("'","")
    doc = doc.split()
    # print(words)
    # for word in words:
        # tokenizated_docs.append(word)
    tokenized_docs.append(doc)

print(tokenized_docs[:20])
print(len(tokenized_docs))

[['toy', 'story', '1995', 'animation', 'childrens', 'comedy'], ['jumanji', '1995', 'adventure', 'childrens', 'fantasy'], ['grumpier', 'old', 'men', '1995', 'comedy', 'romance'], ['waiting', 'to', 'exhale', '1995', 'comedy', 'drama'], ['father', 'of', 'the', 'bride', 'part', 'ii', '1995', 'comedy'], ['heat', '1995', 'action', 'crime', 'thriller'], ['sabrina', '1995', 'comedy', 'romance'], ['tom', 'and', 'huck', '1995', 'adventure', 'childrens'], ['sudden', 'death', '1995', 'action'], ['goldeneye', '1995', 'action', 'adventure', 'thriller'], ['american', 'president', 'the', '1995', 'comedy', 'drama', 'romance'], ['dracula:', 'dead', 'and', 'loving', 'it', '1995', 'comedy', 'horror'], ['balto', '1995', 'animation', 'childrens'], ['nixon', '1995', 'drama'], ['cutthroat', 'island', '1995', 'action', 'adventure', 'romance'], ['casino', '1995', 'drama', 'thriller'], ['sense', 'and', 'sensibility', '1995', 'drama', 'romance'], ['four', 'rooms', '1995', 'thriller'], ['ace', 'ventura:', 'when', 

In [9]:
vocab = set()
for doc in tokenized_docs:
    vocab.update(doc)
print(vocab)
print(len(vocab))

{'ferris', 'cinderella', 'öga', 'ramirez', 'spanish', 'greenberg', 'voyage', 'metal', 'mich', 'treat', 'rainmaker', 'laid', 'periscope', 'neon', 'us', 'swing', 'das', 'sematary', 'blues', 'paradise', 'pot', '1/3:', 'learning', 'sous-sol', 'newmar', 'rage:', 'anything', 'gattaca', 'asylum', 'hill', 'sphere', 'prophecy', 'firm', 'largo', 'lian', 'hendersons', 'trek:', 'che', 'ojos', 'chips', 'cave', 'battle', 'ooze', '1966', 'bound:', 'ghosts', 'milk', 'dove', 'kingpin', 'event', 'boondock', 'rim', 'castaway', 'bud:', 'fancy', 'logans', 'moon', 'amadeus', 'up!', 'hustler', 'piranha', 'truman', 'problem', 'karenina', 'stomper', 'potyomkin', 'seattle', 'trixie', 'me', 'gun:', 'hudsucker', 'chairs', 'stargate', 'singin', 'rendezvous', 'flew', 'natural', 'hunchback', 'crypt', 'sci-fi', 'hi-lo', 'fisher', 'drifter', 'stinks', 'abuelo', 'waterfront', 'cowboys', 'robocop', '1975', 'clay', 'zbogum', 'dance?', 'face/off', 'now', 'monty', 'rascals', 'farm', 'dazed', 'aristocats', 'extra-terrestria

In [10]:
vocab = sorted(list(vocab))
print(vocab[:500])

['$1000000', '&', '-', '1', '1-900', '1/2', '1/2:', '1/3:', '10', '100', '101', '12', '13', '13th', '13th:', '1600', '17', '187', '1900', '1919', '1920', '1921', '1922', '1923', '1925', '1926', '1927', '1928', '1929', '1930', '1931', '1932', '1933', '1934', '1935', '1936', '1937', '1938', '1939', '1940', '1941', '1942', '1943', '1944', '1945', '1946', '1947', '1948', '1949', '1950', '1951', '1952', '1953', '1954', '1955', '1956', '1957', '1958', '1959', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1992:', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '1st', '2', '20', '200', '2000', '20000', '2001:', '2010', '20th', '24', '24-hour', '25', '28', '2:', '3', '3-d', '3000:', '301', '302', '33', '34th', '37th', '39', '3:', '3d', '4', '400', '42', '42nd', '45', '4:'

Column Index

In [11]:
word_to_index = {}

for i, word in enumerate(vocab):
    word_to_index[word] = i

print(word_to_index["1"])

3


Create empty matrix

In [12]:
import numpy as np

num_docs = len(tokenized_docs)
num_words = len(vocab)

#count_matrix = np.zeros((num_docs,num_words))
#this produces error : Unable to allocate 33.9 GiB for an array with shape (1000209, 4546)
#and data type float64. so go with the following

count_matrix = np.zeros((num_docs,num_words),dtype=np.float64)

print(count_matrix.shape)

(3883, 4747)


In [13]:
count_matrix[:,0]

array([0., 0., 0., ..., 0., 0., 0.], shape=(3883,))

In [14]:
from collections import Counter

for row_doc_index, doc in enumerate(tokenized_docs):
    word_count_dic = Counter(doc)
    for word in doc:
        col_word_index = word_to_index[word]
        count_matrix[row_doc_index][col_word_index] = word_count_dic[word]
print(count_matrix.shape)

(3883, 4747)


In [15]:
import pandas as pd

df_matrix = pd.DataFrame(
    count_matrix,
    columns=list(word_to_index.keys()),  # column names = words
    index=[f"Movie_{i}" for i in range(len(tokenized_docs))]  # row names = movies
)

print(df_matrix)

            $1000000    &    -    1  1-900  1/2  1/2:  1/3:   10  100  ...  \
Movie_0          0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...   
Movie_1          0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...   
Movie_2          0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...   
Movie_3          0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...   
Movie_4          0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...   
...              ...  ...  ...  ...    ...  ...   ...   ...  ...  ...  ...   
Movie_3878       0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...   
Movie_3879       0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...   
Movie_3880       0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...   
Movie_3881       0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...   
Movie_3882       0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...   

            zui  zulu  zwerge    à    á    è  école  émile  öga

Initilizing tf_matrix

In [16]:
tf_matrix = np.zeros_like(count_matrix)

for i in range(num_docs):
    total_words = np.sum(count_matrix[i])
    if total_words != 0:
        tf_matrix[i] = count_matrix[i] / total_words
print(tf_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Compute df

In [17]:
print(len(count_matrix[6]))
print(count_matrix[5].shape)

4747
(4747,)


DF(t) = frequency of each words

In [18]:
df = np.zeros(num_words,)
df.shape
for i in range(num_words):
    df[i] = np.sum(count_matrix[:,i] > 0)
print(df)

[ 1. 40.  8. ...  1.  1.  1.]


N = total number of documents (constant)
IDF = log(N/df(t))

In [19]:
N = num_docs
idf = np.log(N/(df+1))

In [20]:
print("tf_matrix.shape : ",tf_matrix.shape)
print("idf.shape : ",idf.shape)
tfidf_matrix = tf_matrix * idf
print("tfidf_matrix : ",tfidf_matrix.shape)

tf_matrix.shape :  (3883, 4747)
idf.shape :  (4747,)
tfidf_matrix :  (3883, 4747)


Done the TF-IDF matrx. 

Now make a user profile to recommend to that user

Get User - 1 's high rated movies

In [21]:
user_id = 1
high_rated = ratings[(ratings['userId'] == user_id) & (ratings['rating'] >= 4)]
high_rated[:5]

,userId,movieId,rating,timestamp
0,1,1193,5,978300760
3,1,3408,4,978300275
4,1,2355,5,978824291
6,1,1287,5,978302039
7,1,2804,5,978300719


In [22]:
liked_movies_ids = high_rated['movieId']
liked_indices = movies[movies['movieId'].isin(liked_movies_ids)].index.tolist()

In [23]:
movies[movies['movieId'].isin(liked_movies_ids)]["title"]

0                                Toy Story (1995)
47                              Pocahontas (1995)
148                              Apollo 13 (1995)
257     Star Wars: Episode IV - A New Hope (1977)
523                       Schindler's List (1993)
527                     Secret Garden, The (1993)
584                                Aladdin (1992)
590        Snow White and the Seven Dwarfs (1937)
591                   Beauty and the Beast (1991)
604                                  Fargo (1996)
773           Hunchback of Notre Dame, The (1996)
907                      Wizard of Oz, The (1939)
926                                   Gigi (1958)
1009                            Cinderella (1950)
1015                          Mary Poppins (1964)
1016                                 Dumbo (1941)
1022                   Sound of Music, The (1965)
1081            E.T. the Extra-Terrestrial (1982)
1176       One Flew Over the Cuckoo's Nest (1975)
1189                 To Kill a Mockingbird (1962)


In [24]:
print(liked_indices)

for idx in liked_indices[:3]:
    print("Index:", idx)
    print("Movie title:", movies.iloc[idx]['title'])
    print("Vector shape:", df_matrix.iloc[idx].shape)
    print()
    

[0, 47, 148, 257, 523, 527, 584, 590, 591, 604, 773, 907, 926, 1009, 1015, 1016, 1022, 1081, 1176, 1189, 1226, 1250, 1267, 1506, 1526, 1672, 1768, 1838, 1892, 1893, 1949, 1959, 2225, 2286, 2329, 2623, 2693, 2722, 2728, 2735, 2849, 3036, 3045, 3117, 3339]
Index: 0
Movie title: Toy Story (1995)
Vector shape: (4747,)

Index: 47
Movie title: Pocahontas (1995)
Vector shape: (4747,)

Index: 148
Movie title: Apollo 13 (1995)
Vector shape: (4747,)



Build the User Profile Vector

In [25]:
user_profile = np.mean(tfidf_matrix[liked_indices],axis=0)
print(user_profile)

[0.         0.         0.01037118 ... 0.         0.         0.        ]


Compute Cosine Similarity (User vs All Movies)

In [26]:
user_norm = np.sqrt(np.sum(user_profile ** 2))
movie_norm = np.sqrt(np.sum(tfidf_matrix**2, axis=1))
dot_product = tfidf_matrix @ user_profile

similarities = dot_product / (user_norm * movie_norm)

similarity = np.nan_to_num(similarities)
similarity[1]

np.float64(0.1830199064650918)

Remove Movies Already Seen

In [27]:
similarity[liked_indices] = -1
# so these don't get recommendated

Get Top 10 Recommendations

In [28]:
top_ten_indices = np.argsort(similarity)[::-1][:10]
recommended_movies = movies.iloc[top_ten_indices]["title"]
print(recommended_movies)

3090           Fantasia 2000 (1999)
1642               Anastasia (1997)
2012     Little Mermaid, The (1989)
2023    Return of Jafar, The (1993)
1262                Fantasia (1940)
2027         Sleeping Beauty (1959)
360           Lion King, The (1994)
2009        Jungle Book, The (1967)
2490         King and I, The (1999)
2030       Song of the South (1946)
Name: title, dtype: object


Verifying output

In [ ]:
print(movies.iloc[liked_indices]["title"])

0                                Toy Story (1995)
47                              Pocahontas (1995)
148                              Apollo 13 (1995)
257     Star Wars: Episode IV - A New Hope (1977)
523                       Schindler's List (1993)
527                     Secret Garden, The (1993)
584                                Aladdin (1992)
590        Snow White and the Seven Dwarfs (1937)
591                   Beauty and the Beast (1991)
604                                  Fargo (1996)
773           Hunchback of Notre Dame, The (1996)
907                      Wizard of Oz, The (1939)
926                                   Gigi (1958)
1009                            Cinderella (1950)
1015                          Mary Poppins (1964)
1016                                 Dumbo (1941)
1022                   Sound of Music, The (1965)
1081            E.T. the Extra-Terrestrial (1982)
1176       One Flew Over the Cuckoo's Nest (1975)
1189                 To Kill a Mockingbird (1962)


In [33]:
print(similarity[top_ten_indices])
# this is pretty decent

[0.40740446 0.39698572 0.37820824 0.35804528 0.35721462 0.35063693
 0.34723844 0.33527492 0.32516881 0.32484944]


### Evaluation

Get user data

In [ ]:
user_id = 1

user_data = ratings[(ratings["userId"] == user_id)]
liked_movies = user_data[user_data["rating"] >= 4]
liked_movies.head(5)

,userId,movieId,rating,timestamp
0,1,1193,5,978300760
3,1,3408,4,978300275
4,1,2355,5,978824291
6,1,1287,5,978302039
7,1,2804,5,978300719
